const productos = [
  {
    id: 1,
    nombre: "Cama Neuquen",
    precio: 199000,
    descripcion:
      "Mesa ratona en nogal macizo con líneas limpias y ensambles a la vista.",
    madera: "Nogal",
    terminacion: "Aceite de tung + cera",
    medidas: "110 × 55 × 38 cm",
    features: [
      "Ensambles tradicionales",
      "Vidrio templado 8mm",
      "Fieltros antideslizantes",
    ],
    img: "../assets/img/productos/camaNeuquen.png",
  },
  {
    id: 2,
    nombre: "Biblioteca Recoleta",
    precio: 89000,
    descripcion:
      "Estructura de guatambú y tapizado en lino. Diseñada para durar.",
    madera: "Guatambú",
    terminacion: "Laca al agua mate",
    medidas: "45 × 50 × 82 cm",
    features: ["Tapizado desmontable", "Refuerzos ocultos", "Protección UV"],
    img: "../assets/img/productos/bibliotecaRecoleta.png",
  },
  {
    id: 3,
    nombre: "Aparador Uspallata",
    precio: 359000,
    descripcion:
      "Aparador en roble con puertas en caña. Almacenamiento elegante.",
    madera: "Roble europeo",
    terminacion: "Aceite danés",
    medidas: "160 × 45 × 80 cm",
    features: ["Correderas soft-close", "Puertas en caña", "Zócalo regulable"],
    img: "../assets/img/productos/aparadorUspallata.png",
  },
  {
    id: 4,
    nombre: "Mesa de Centro Araucaria",
    precio: 98799,
    descripcion:
      "Mesa de centro en pino araucaria, ideal para livings modernos.",
    madera: "Pino Araucaria",
    terminacion: "Barniz satinado",
    medidas: "100 × 60 × 40 cm",
    features: [
      "Estructura reforzada",
      "Bordes redondeados",
      "Fieltros protectores",
    ],
    img: "../assets/img/productos/mesaDeCentroAraucaria.png",
  },
  {
    id: 5,
    nombre: "Butaca Mendoza",
    precio: 98799,
    descripcion:
      "Butaca en guatambú tapizada en lino natural. Estilo clásico y confortable.",
    madera: "Guatambú",
    terminacion: "Laca al agua",
    medidas: "70 × 75 × 85 cm",
    features: ["Tapizado lavable", "Asiento acolchado", "Respaldo ergonómico"],
    img: "../assets/img/productos/butacaMendoza.png",
  },
  {
    id: 6,
    nombre: "Mesa de Noche Aconcagua",
    precio: 120000,
    descripcion:
      "Mesa de noche con cajón en madera maciza. Compacta y funcional.",
    madera: "Roble macizo",
    terminacion: "Aceite natural",
    medidas: "50 × 40 × 55 cm",
    features: [
      "Cajón con correderas metálicas",
      "Tiradores de bronce",
      "Patas torneadas",
    ],
    img: "../assets/img/productos/mesaDeNocheAconcagua.png",
  },
  {
    id: 7,
    nombre: "Sofá Patagonia",
    precio: 299000,
    descripcion:
      "Sofá de tres cuerpos en lino, con estructura de madera de lenga.",
    madera: "Lenga",
    terminacion: "Aceite de lino",
    medidas: "220 × 90 × 80 cm",
    features: [
      "Cojines desmontables",
      "Tapizado premium",
      "Costuras reforzadas",
    ],
    img: "../assets/img/productos/sofaPatagonia.png",
  },
  {
    id: 8,
    nombre: "Mesa Comedor Pampa",
    precio: 89000,
    descripcion: "Mesa de comedor en madera maciza para 6 personas.",
    madera: "Paraíso",
    terminacion: "Laca poliuretánica",
    medidas: "180 × 90 × 75 cm",
    features: [
      "Capacidad para 6",
      "Patas desmontables",
      "Superficie resistente a manchas",
    ],
    img: "../assets/img/productos/mesaComedorPampa.png",
  },
  {
    id: 9,
    nombre: "Sillón Copacabana",
    precio: 56799,
    descripcion:
      "Sillón individual de diseño contemporáneo en lino y madera maciza.",
    madera: "Guatambú",
    terminacion: "Barniz transparente",
    medidas: "80 × 85 × 90 cm",
    features: ["Tapizado acolchado", "Apoyabrazos anchos", "Base robusta"],
    img: "../assets/img/productos/sillonCopacabana.png",
  },
  {
    id: 10,
    nombre: "Sillas Córdoba",
    precio: 36999,
    descripcion:
      "Juego de sillas en madera maciza con asiento tapizado en lino.",
    madera: "Roble",
    terminacion: "Aceite natural",
    medidas: "45 × 50 × 90 cm",
    features: ["Asiento acolchado", "Apilables", "Tratamiento anti-humedad"],
    img: "../assets/img/productos/sillasCordoba.png",
  },
  {
    id: 11,
    nombre: "Silla de Trabajo Belgrano",
    precio: 119999,
    descripcion:
      "Silla ergonómica en madera y cuero ecológico. Ideal para oficina.",
    madera: "Cedro",
    terminacion: "Laca semimate",
    medidas: "65 × 65 × 115 cm",
    features: ["Altura regulable", "Ruedas reforzadas", "Respaldo reclinable"],
    img: "../../assets/img/productos/sillaDeTrabajoBelgrano.png",
  },
  {
    id: 12,
    nombre: "Escritorio Costa",
    precio: 125999,
    descripcion:
      "Escritorio minimalista en madera maciza con amplio espacio de guardado.",
    madera: "Pino Oregon",
    terminacion: "Barniz mate",
    medidas: "140 × 60 × 75 cm",
    features: ["Cajón oculto", "Superficie amplia", "Estructura reforzada"],
    img: "../assets/img/productos/escritorioCosta.png",
  },
];
